spring.application.name=AgriConnect
spring.datasource.url=jdbc:mysql://localhost:3306/agriconnect
spring.datasource.username=root
spring.datasource.password=MynaV@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true